# Generated by Django 3.0.5 on 2020-06-22 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('A', 'Action'), ('R', 'Role-Playing'), ('P', 'Puzzle'), ('S', 'Sports')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
