# Generated by Django 3.0.5 on 2020-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200623_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='msg',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('A', 'Action'), ('P', 'Puzzle'), ('R', 'Role-Playing'), ('S', 'Sports')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('5', '5 - Amazing'), ('4', '4 - Good'), ('3', '3 - Average'), ('2', '2 - Ehh'), ('1', '1 - Terrible')], default=('3', '3 - Average'), max_length=1),
        ),
    ]
